g.V().fail('There's been an error.')